# Generated by Django 4.0.6 on 2022-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('destination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_country', models.CharField(max_length=100)),
                ('origin', models.IntegerField()),
                ('destination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=200)),
                ('date', models.DateField(null=True, unique=True)),
                ('select', models.CharField(choices=[('self', 'Self'), ('other', 'Other')], max_length=200)),
                ('image', models.ImageField(upload_to='services')),
            ],
        ),
    ]
