# Generated by Django 4.0.6 on 2022-11-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('Destination_country', models.CharField(max_length=100)),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('from_whom', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
