# Generated by Django 4.0.6 on 2022-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='select',
            new_name='delivery_hand',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services',
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
