# Generated by Django 4.0.6 on 2022-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_select_services_delivery_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=10)),
                ('vehicle_no', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
