# Generated by Django 4.0.6 on 2022-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_orderdetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('shipment', 'started'), ('shipment', 'in process'), ('shipment', 'completed')], max_length=20, null=True),
        ),
    ]
