# Generated by Django 4.0.6 on 2022-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Destination_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
