# Generated by Django 4.0.2 on 2022-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_orderdetails_destination_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldetails',
            name='item_weight',
            field=models.IntegerField(),
        ),
    ]
