# Generated by Django 4.1 on 2022-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_rename_users_orderdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='picked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
