# Generated by Django 4.1 on 2022-11-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.drivers'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='issue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('in_process', 'in_process'), ('completed', 'completed')], max_length=200, null=True),
        ),
    ]
