# Generated by Django 4.0.2 on 2022-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_parceldetails_user_alter_orderdetails_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='picked',
            field=models.BooleanField(null=True),
        ),
    ]
