# Generated by Django 4.1 on 2022-12-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_rename_destination_domestic_destination_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domestic',
            old_name='destination_pincode',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='domestic',
            old_name='origin_pincode',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='parceldetails',
            name='delivery_hand',
        ),
    ]
