# Generated by Django 4.1 on 2022-12-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0031_drivers_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='name',
        ),
        migrations.AddField(
            model_name='drivers',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
