# Generated by Django 4.1 on 2022-12-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_remove_drivers_name_drivers_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Domestic',
        ),
        migrations.DeleteModel(
            name='International',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='drivers',
            name='full_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver_orders',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.drivers'),
        ),
        migrations.AddField(
            model_name='driver_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orderdetails'),
        ),
    ]
