# Generated by Django 4.1 on 2022-12-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=30)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('proof_type', models.CharField(max_length=50, null=True)),
                ('proof_id', models.CharField(max_length=120, null=True)),
                ('verified', models.BooleanField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('pickup_date', models.DateField(null=True)),
                ('parcel_image', models.ImageField(upload_to='images')),
                ('receiver_name', models.CharField(max_length=200, null=True)),
                ('receiver_phone', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('Destination_country', models.CharField(editable=False, max_length=100, null=True)),
                ('item_weight', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('from_whom', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(editable=False, null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('in_process', 'in_process'), ('completed', 'completed')], max_length=200, null=True)),
                ('picked', models.BooleanField(null=True)),
                ('receiver_name', models.CharField(max_length=200, null=True)),
                ('receiver_phone', models.CharField(max_length=200, null=True)),
                ('aadhar_no', models.IntegerField(null=True)),
                ('transporter', models.CharField(max_length=200, null=True)),
                ('driver', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.drivers')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.drivers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('issue', models.TextField()),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
