# Generated by Django 4.1 on 2022-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
