# Generated by Django 4.0.2 on 2022-12-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_driver_orders_drivers_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='transporter',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.drivers'),
        ),
    ]
