# Generated by Django 4.0.2 on 2022-11-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='vehicle_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='vehicle_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
