# Generated by Django 4.0.2 on 2022-11-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_parceldetails_delete_parcel_delete_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='OrderDetails',
        ),
    ]
