# Generated by Django 4.0.6 on 2022-12-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_orderdetails_from_whom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.drivers'),
        ),
    ]
