# Generated by Django 4.1 on 2022-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_admin_driver_driver_details_update_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver_details_update',
        ),
        migrations.AddField(
            model_name='admin_driver',
            name='address',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='admin_driver',
            name='govt_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='admin_driver',
            name='id_type',
            field=models.CharField(choices=[('Aadhar_no', 'Aadhar no'), ('Driving_license', 'Driving license'), ('Pancard', 'Pancard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admin_driver',
            name='new_password',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin_driver',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin_driver',
            name='temp_password',
            field=models.CharField(max_length=12),
        ),
    ]
