# Generated by Django 4.0.2 on 2022-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_admin_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_driver',
            name='name',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
