# Generated by Django 4.0.2 on 2022-11-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='user',
            new_name='users',
        ),
    ]
