# Generated by Django 4.0.6 on 2022-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_admin_driver_created_admin_driver_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_driver',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='admin_driver',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
