# Generated by Django 4.0.6 on 2022-12-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_admin_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_driver',
            name='name',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
