# Generated by Django 4.1 on 2022-11-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_orderdetails_picked_alter_orderdetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deiver_name', models.CharField(max_length=10)),
                ('driver_mob', models.CharField(max_length=10)),
            ],
        ),
    ]
