# Generated by Django 4.1 on 2022-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_orderdetails_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='picked',
            field=models.BooleanField(),
        ),
    ]
