# Generated by Django 4.0.6 on 2022-12-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_admin_driver_name'),
        ('service', '0026_alter_orderdetails_picked'),
    ]

    operations = [
    ]
